server:
    port: 5555

grpc:
    server:
        port: 9090
        security:
            enabled: false
    client:
      service:
        address: localhost:9595
        negotiation-type: plaintext


spring:
    application:
        name: api
    datasource:
        url: jdbc:postgresql://localhost:5432/budget_manager
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        database: postgresql
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: none
    web:
        resources:
            add-mappings: false

api:
    prefix: /api/v1

springdoc:
    swagger-ui:
        path: /api/v1/swagger-ui
        operations-sorter: method
    api-docs:
        path: /api/v1/doc

security:
    public-paths:
        - "/api/v1/auth/**"
        - "/v3/api-docs/**"
        - "/api/v1/swagger-ui/**"
        - "/api/v1/doc/**"
    jwt:
        secret: GO6Mz+3kwgH6ybMnaeBGiMp3Anx1jKYOtPJEd3GmBf2xdZHLAgbQzXgzgxQgZhA22YEmQE/TnMvr1KsFsjDu0w==
        access:
            expiration-ms: 900000 # 15 minutes
        refresh:
            expiration-ms: 1209600000 # 14 days
